<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Bantexx</Authors>
    <Description>Union of two libs: zeebe-client-scharp and zeebe-client-csharp-accelerator for custom develop.
Fork of https://github.com/VonDerBeck/zeebe-client-csharp-accelerator</Description>
    <Product>Accelerator extension Fork</Product>
    <RepositoryUrl>https://github.com/Bantexx/zeebe-client-accelerator-fork</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageId>zb-client-accelerator-fork</PackageId>
    <PackageProjectUrl>https://github.com/Bantexx/zeebe-client-accelerator-fork</PackageProjectUrl>
    <PackageTags>zeebe;zb;zb-csharp;zb-client;grpc</PackageTags>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.0.2</Version>
    <PackageIcon>zeebe-logo.png</PackageIcon>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeClientAssemblyInPackage</TargetsForTfmSpecificContentInPackage>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>1.0.2</AssemblyVersion>
    <FileVersion>1.0.2</FileVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
    <WarningLevel>7</WarningLevel>
  </PropertyGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\Zeebe.Client\Client\Client.csproj" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Google.Protobuf" Version="3.34.1" />
    <PackageReference Include="Grpc.Auth" Version="2.76.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.19.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="zeebe-logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="IncludeClientAssemblyInPackage">
    <ItemGroup>
      <TfmSpecificPackageFile Include="..\..\Zeebe.Client\Client\bin\$(Configuration)\$(TargetFramework)\Client.dll"
                              Condition="Exists('..\..\Zeebe.Client\Client\bin\$(Configuration)\$(TargetFramework)\Client.dll')">
        <PackagePath>lib/$(TargetFramework)</PackagePath>
      </TfmSpecificPackageFile>
    </ItemGroup>
  </Target>
  
</Project>
